Instantiate devbox differently to prevent command escaping issues

diff --git a/dssh b/dssh
--- a/dssh
+++ b/dssh
@@ -4,165 +4,148 @@ if [[ $0 != dssh || -n $ZSH_SCRIPT ]]; then
     typeset ZSH_DSSH_DIR=${0:h}
 fi
 
-if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
-  devbox run -c "$ZSH_DSSH_DIR" dssh "$@"
-  return $?
-fi
-
 set +m
 set -o pipefail
 
-local WAS_UPDATED=false
-local DEFAULT_PARAMETERS=( "-o ConnectTimeout=10" )
-local PUBLIC_DNS_NAME_PATTERN="ec2-.+"
-
-_usage() {
-  echo
-  echo "Locates and connects to AWS servers via SSH."
-  echo
-  echo "Usage: dssh [ssh options] [options] tags [tags ...]"
-  echo ""
-  _dssh_tag_usage
-  echo "SSH OPTIONS:"
-  echo "    Flags:   -4 | -6 | -A | -a | -C | -f | -G | -g | -K | -k | -M"
-  echo "             -q | -s | -T | -t | -V | -X | -x | -Y | -y"
-  echo "    Options: -B | -b | -c | -D | -E | -e | -F | -I | -i | -J | -l"
-  echo "             -m | -O | -o | -p | -Q | -R | -S | -W | -w"
-  echo ""
-  echo "OPTIONS:"
-  echo "    --tmux, --tmux=session, --no_tmux  enable/disable tmux session"
-  echo "    --command=COMMAND                  run the specified command and exit"
-  echo "    --tunnel=PORT                      open a tunnel for the specified port"
-  _dssh_common_usage
-}
-
-_parse_parameter() {
-  local shift_count=1
-  case "$1" in
-    -4 | -6 | -A | -a | -C | -f | -G | -g | -K | -k | -M | -q | -s | -T | -t | -V | -X | -x | -Y | -y)
-      _dssh_add_ssh_option "$1"
-    ;;
-    -B | -b | -c | -D | -E | -e | -F | -I | -i | -J | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w)
-      _dssh_add_ssh_option "$1 $2"
-      shift_count=2
-    ;;
-    -B\ * | -b\ * | -c\ * | -D\ * | -E\ * | -e\ * | -F\ * | -I\ * | -i\ * | -J\ * | -l\ * | -m\ * | -O\ * | -o\ * | -p\ * | -Q\ * | -R\ * | -S\ * | -W\ * | -w\ *)
-      _dssh_add_ssh_option "$1"
-    ;;
-    --tmux)
-      enable_tmux="default"
-    ;;
-    --tmux=*)
-      enable_tmux="${1#*=}"
-      if [[ "$enable_tmux" == "" ]]; then
-        _dssh_perror "--tmux=<SESSION> cannot have an empty session"
-      fi
-    ;;
-    --no_tmux)
-      enable_tmux=""
-    ;;
-    --tunnel=*)
-      tunnel="${1#*=}"
-    ;;
-    -c=* | --command=*)
-      command_string="${1#*=}"
-    ;;
-    -v | -vv | -vvv | -vvvv)
-      _dssh_add_ssh_option "-$(printf 'v%.0s' {1..$verbose_level})"
-    ;;
-    *)
-      if [[ "$1" =~ ^-[46AaCfGgKkMNnqsTtVXxYy]+$ ]]; then
-        for char in $(echo "${1:1}" | fold -w1); do
-          _parse_parameter "-$char"
-        done
-      else
-        _dssh_parse_common_parameters "$1"
-        shift_count=$?
-      fi
-    ;;
-  esac
-  return $shift_count
-}
-
-_dssh_prepare_dssh_locking
-
-if [[ $# -eq 0 ]]; then
-  _dssh_perror "wrong number of input parameters [$#]"
-  _usage
-  return $_dssh_e_noargs
-fi
-
-local python_installed=false
-local refresh_enabled=false
-local ip_mode="AUTO"
-local verbose_level=0
-local ssh_options=()
-local tags=()
-local enable_tmux=""
-local command_string=""
-local tunnel=""
-if ! _dssh_parse_parameters ".dsshrc" "$@"; then
-  return $_dssh_e_noerror
-fi
-
-if [[ "$enable_tmux" =~ [^a-zA-Z0-9_-] ]]; then
-  _dssh_perror "--tmux=<SESSION> must have a session name that is composed of only dash, underscore, and alphanumeric characters"
-fi
-
-if [[ "${#tunnel}" -gt 0 && "${#command_string}" -gt 0 ]]; then
-  _dssh_perror "--tunnel and --command cannot be specified at the same time"
-fi
-
-_dssh_init
-
-local addr=""
-local desc=""
-local name=""
-if [[ ${#tags[@]} -eq 1 && "${tags[1]}" =~ $_dssh_public_fqdn_target ]]; then
-  addr="${tags[1]}"
-else
-  local info=""
-  info="$(_dssh_resolve_target "${tags[@]}")"
-  if [[ "$?" -eq 1 ]]; then
-    WAS_UPDATED=true
+(
+  if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
+    export DEVBOX_SHELL_ENABLED=1
+    devbox -c "$ZSH_DSSH_DIR" --quiet install &> /dev/null || fatal _dssh_pfatal "failed to install devbox packages: $?"
+    local shell_env
+    shell_env="$(devbox -c "$ZSH_DSSH_DIR" --quiet shellenv | tac | sed -n '/^export /,$p' | tac | grep -v 'XPC_SERVICE_NAME')" || fatal _dssh_pfatal "failed to get devbox env: $?"
+    eval "$shell_env" || fatal _dssh_pfatal "failed to set devbox env: $?"
   fi
-  if [ -z "$info" ]; then
-    _dssh_update_inventories
+
+  local WAS_UPDATED=false
+  local DEFAULT_PARAMETERS=( "-o ConnectTimeout=10" )
+  local PUBLIC_DNS_NAME_PATTERN="ec2-.+"
+
+  _usage() {
+    echo
+    echo "Locates and connects to AWS servers via SSH."
+    echo
+    echo "Usage: dssh [ssh options] [options] tags [tags ...]"
+    echo ""
+    _dssh_tag_usage
+    echo "SSH OPTIONS:"
+    echo "    Flags:   -4 | -6 | -A | -a | -C | -f | -G | -g | -K | -k | -M"
+    echo "             -q | -s | -T | -t | -V | -X | -x | -Y | -y"
+    echo "    Options: -B | -b | -c | -D | -E | -e | -F | -I | -i | -J | -l"
+    echo "             -m | -O | -o | -p | -Q | -R | -S | -W | -w"
+    echo ""
+    echo "OPTIONS:"
+    echo "    --tmux, --tmux=session, --no_tmux  enable/disable tmux session"
+    echo "    --command=COMMAND                  run the specified command and exit"
+    echo "    --tunnel=PORT                      open a tunnel for the specified port"
+    _dssh_common_usage
+  }
+
+  _parse_parameter() {
+    local shift_count=1
+    case "$1" in
+      -4 | -6 | -A | -a | -C | -f | -G | -g | -K | -k | -M | -q | -s | -T | -t | -V | -X | -x | -Y | -y)
+        _dssh_add_ssh_option "$1"
+      ;;
+      -B | -b | -c | -D | -E | -e | -F | -I | -i | -J | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w)
+        _dssh_add_ssh_option "$1 $2"
+        shift_count=2
+      ;;
+      -B\ * | -b\ * | -c\ * | -D\ * | -E\ * | -e\ * | -F\ * | -I\ * | -i\ * | -J\ * | -l\ * | -m\ * | -O\ * | -o\ * | -p\ * | -Q\ * | -R\ * | -S\ * | -W\ * | -w\ *)
+        _dssh_add_ssh_option "$1"
+      ;;
+      --tmux)
+        enable_tmux="default"
+      ;;
+      --tmux=*)
+        enable_tmux="${1#*=}"
+        if [[ "$enable_tmux" == "" ]]; then
+          _dssh_perror "--tmux=<SESSION> cannot have an empty session"
+        fi
+      ;;
+      --no_tmux)
+        enable_tmux=""
+      ;;
+      --tunnel=*)
+        tunnel="${1#*=}"
+      ;;
+      -c=* | --command=*)
+        command_string="${1#*=}"
+      ;;
+      -v | -vv | -vvv | -vvvv)
+        _dssh_add_ssh_option "-$(printf 'v%.0s' {1..$verbose_level})"
+      ;;
+      *)
+        if [[ "$1" =~ ^-[46AaCfGgKkMNnqsTtVXxYy]+$ ]]; then
+          for char in $(echo "${1:1}" | fold -w1); do
+            _parse_parameter "-$char"
+          done
+        else
+          _dssh_parse_common_parameters "$1"
+          shift_count=$?
+        fi
+      ;;
+    esac
+    return $shift_count
+  }
+
+  _dssh_prepare_dssh_locking
+
+  if [[ $# -eq 0 ]]; then
+    _dssh_perror "wrong number of input parameters [$#]"
+    _usage
+    return $_dssh_e_noargs
+  fi
+
+  local python_installed=false
+  local refresh_enabled=false
+  local ip_mode="AUTO"
+  local verbose_level=0
+  local ssh_options=()
+  local tags=()
+  local enable_tmux=""
+  local command_string=""
+  local tunnel=""
+  if ! _dssh_parse_parameters ".dsshrc" "$@"; then
+    return $_dssh_e_noerror
+  fi
+
+  if [[ "$enable_tmux" =~ [^a-zA-Z0-9_-] ]]; then
+    _dssh_perror "--tmux=<SESSION> must have a session name that is composed of only dash, underscore, and alphanumeric characters"
+  fi
+
+  if [[ "${#tunnel}" -gt 0 && "${#command_string}" -gt 0 ]]; then
+    _dssh_perror "--tunnel and --command cannot be specified at the same time"
+  fi
+
+  _dssh_init
+
+  local addr=""
+  local desc=""
+  local name=""
+  if [[ ${#tags[@]} -eq 1 && "${tags[1]}" =~ $_dssh_public_fqdn_target ]]; then
+    addr="${tags[1]}"
+  else
+    local info=""
     info="$(_dssh_resolve_target "${tags[@]}")"
     if [[ "$?" -eq 1 ]]; then
       WAS_UPDATED=true
     fi
     if [ -z "$info" ]; then
-      _dssh_pwarn "Host '${tags[*]}' not found in inventory.  Attempting to connect anyway..."
-      addr="${tags[*]}"
-    fi
-  fi
-  if [[ "$addr" == "" ]]; then
-    local count=$(echo "$info" | wc -l)
-    if [[ $count -gt 1 ]]; then
-      if _dssh_is_inventory_old; then
-        _dssh_update_inventories
+      _dssh_update_inventories
+      info="$(_dssh_resolve_target "${tags[@]}")"
+      if [[ "$?" -eq 1 ]]; then
+        WAS_UPDATED=true
       fi
-      _dssh_prompt_server
-      local result="$?"
-      if [[ "$result" -eq -1 ]]; then
-        return $_dssh_e_noerror
-      elif [[ "$result" -gt 0 ]]; then
-        return $result
+      if [ -z "$info" ]; then
+        _dssh_pwarn "Host '${tags[*]}' not found in inventory.  Attempting to connect anyway..."
+        addr="${tags[*]}"
       fi
     fi
-    addr=$(echo $info | awk -F, '{print $2}')
-    name=$(echo $info | awk -F, '{print $1}')
-    desc=" ($name) [$(echo $info | awk -F, '{print $4}')]"
-    if [[ "$addr" =~ $PUBLIC_DNS_NAME_PATTERN ]] && ! nc -G3 -z $addr 22 &>/dev/null; then
-      if [[ "$WAS_UPDATED" == "false" ]]; then
-        _dssh_update_inventories
-        info="$(_dssh_resolve_target "$name")"
-        if [[ "$?" -eq 1 ]]; then
-          WAS_UPDATED=true
-        fi
-        if [[ "$info" == "" ]]; then
-          info="$(_dssh_resolve_target "${tags[@]}")"
+    if [[ "$addr" == "" ]]; then
+      local count=$(echo "$info" | wc -l)
+      if [[ $count -gt 1 ]]; then
+        if _dssh_is_inventory_old; then
+          _dssh_update_inventories
         fi
         _dssh_prompt_server
         local result="$?"
@@ -171,51 +154,73 @@ else
         elif [[ "$result" -gt 0 ]]; then
           return $result
         fi
-        addr=$(echo $info | awk -F, '{print $2}')
-        desc=$(echo $info | awk -F, '{print "(" $1 ") [" $3 "]"}')
+      fi
+      addr=$(echo $info | awk -F, '{print $2}')
+      name=$(echo $info | awk -F, '{print $1}')
+      desc=" ($name) [$(echo $info | awk -F, '{print $4}')]"
+      if [[ "$addr" =~ $PUBLIC_DNS_NAME_PATTERN ]] && ! nc -G3 -z $addr 22 &>/dev/null; then
+        if [[ "$WAS_UPDATED" == "false" ]]; then
+          _dssh_update_inventories
+          info="$(_dssh_resolve_target "$name")"
+          if [[ "$?" -eq 1 ]]; then
+            WAS_UPDATED=true
+          fi
+          if [[ "$info" == "" ]]; then
+            info="$(_dssh_resolve_target "${tags[@]}")"
+          fi
+          _dssh_prompt_server
+          local result="$?"
+          if [[ "$result" -eq -1 ]]; then
+            return $_dssh_e_noerror
+          elif [[ "$result" -gt 0 ]]; then
+            return $result
+          fi
+          addr=$(echo $info | awk -F, '{print $2}')
+          desc=$(echo $info | awk -F, '{print "(" $1 ") [" $3 "]"}')
+        fi
       fi
     fi
   fi
-fi
 
-if [[ "${addr}" == "" ]]; then
-  _dssh_pverbose "No server was found"
-  return $_dssh_e_noserver
-fi
-
-echo "" 1>&2
-local connection_message="Connecting to"
-local -a ssh_command=( "ssh" )
-if [[ "$enable_tmux" != "" ]]; then
-  if [[ "${#command_string}" -eq 0 && "${#tunnel}" -eq 0 ]]; then
-    _dssh_pverbose "Enabling tmux session"
-    command_string="tmux -CC new -A -s '${enable_tmux}'"
-    ssh_options+=( "-tt" )
-  elif [[ "${#command_string}" -gt 0 ]]; then
-    _dssh_pverbose "Command specified, tmux session disabled"
-  else
-    _dssh_pverbose "Tunneling enabled, tmux session disabled"
+  if [[ "${addr}" == "" ]]; then
+    _dssh_pverbose "No server was found"
+    return $_dssh_e_noserver
   fi
-fi
-if [[ "${#command_string}" -gt 0 ]]; then
-  connection_message="Running command \`$command_string\` on"
-fi
-if [[ "${#tunnel}" -gt 0 ]]; then
-  connection_message="Opening tunnel for port \`$tunnel\` to"
-fi
-if [[ "${#ssh_options[@]}" -gt 0 ]]; then
-  read -rA opts <<<"${ssh_options[@]}"
-  for opt in "${opts[@]}"; do
-    ssh_command+=( "$opt" )
-  done
-fi
-if [[ "${#tunnel}" -gt 0 ]]; then
-  ssh_command+=( "-nNT" "-L" "${tunnel}:localhost:${tunnel}" )
-fi
-ssh_command+=( "${addr}" )
-if [[ "${#command_string}" -gt 0 ]]; then
-  ssh_command+=( "${command_string}" )
-fi
-_dssh_pverbose "$connection_message ${addr}${desc}..."
-${ssh_command[@]}
-return $?
+
+  echo "" 1>&2
+  local connection_message="Connecting to"
+  local -a ssh_command=( "ssh" )
+  if [[ "$enable_tmux" != "" ]]; then
+    if [[ "${#command_string}" -eq 0 && "${#tunnel}" -eq 0 ]]; then
+      _dssh_pverbose "Enabling tmux session"
+      command_string="tmux -CC new -A -s '${enable_tmux}'"
+      ssh_options+=( "-tt" )
+    elif [[ "${#command_string}" -gt 0 ]]; then
+      _dssh_pverbose "Command specified, tmux session disabled"
+    else
+      _dssh_pverbose "Tunneling enabled, tmux session disabled"
+    fi
+  fi
+  if [[ "${#command_string}" -gt 0 ]]; then
+    connection_message="Running command \`$command_string\` on"
+  fi
+  if [[ "${#tunnel}" -gt 0 ]]; then
+    connection_message="Opening tunnel for port \`$tunnel\` to"
+  fi
+  if [[ "${#ssh_options[@]}" -gt 0 ]]; then
+    read -rA opts <<<"${ssh_options[@]}"
+    for opt in "${opts[@]}"; do
+      ssh_command+=( "$opt" )
+    done
+  fi
+  if [[ "${#tunnel}" -gt 0 ]]; then
+    ssh_command+=( "-nNT" "-L" "${tunnel}:localhost:${tunnel}" )
+  fi
+  ssh_command+=( "${addr}" )
+  if [[ "${#command_string}" -gt 0 ]]; then
+    ssh_command+=( "${command_string}" )
+  fi
+  _dssh_pverbose "$connection_message ${addr}${desc}..."
+  ${ssh_command[@]}
+  return $?
+)
diff --git a/dwhois b/dwhois
--- a/dwhois
+++ b/dwhois
@@ -4,115 +4,120 @@ if [[ $0 != dwhois || -n $ZSH_SCRIPT ]]; then
     typeset ZSH_DSSH_DIR=${0:h}
 fi
 
-if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
-  devbox run -c "$ZSH_DSSH_DIR" dwhois "$@"
-  return $?
-fi
-
 set +m
 set -o pipefail
 
-local WAS_UPDATED=false
-local -a sort_command=("cat" "-u")
-local format="FULL"
-_usage() {
-  echo
-  echo "Locates servers in the inventory."
-  echo
-  echo "Usage: dwhois tags [tags ...]"
-  echo ""
-  _dssh_tag_usage
-  echo "OPTIONS:"
-  echo "    --format=[IP|INSTANCE_ID|SHORT|FULL|RAW]    format of details tp print about the servers (default: FULL)"
-  _dssh_common_usage
-}
-_parse_parameter() {
-  local shift_count=1
-  case "$1" in
-    -f=* | --format=*)
-      format="${1#*=}"
-      format="${format:u}"
-      case $format in
-        SHORT | INSTANCE_ID | IP | FULL | RAW)
-          ;;
-        *)
-          _dssh_perror "unsupported format [$format]"
-          _usage
-          return $_dssh_e_noargs
-          ;;
-        esac
-    ;;
-    -v | -vv | -vvv | -vvvv)
-    ;;
-    *)
-      _dssh_parse_common_parameters "$1"
-      shift_count=$?
-    ;;
-  esac
-  return $shift_count
-}
-function _print_hosts_full() {
-  local max_host_length="$(echo "$1" | cut -d "," -f 1 | awk '{print length}' | sort -nr | head -1)"
-  max_host_length="$((max_host_length+1))"
-  local public_icon=$'\uf0c2'
-  local private_icon=$'\uf023'
-  echo "$1" | awk -F ',' "{printf \"%s%s%s%3s: %s%-*s%s (%s)  [%s]\n\", \"$_dssh_color_prefix\", \$12, \"$_dssh_color_suffix\", NR, \"$_dssh_nc\", $max_host_length-1, \$1, \"$_dssh_gray\", \$9, \$7}{if (length(\$6) > 0) printf \"       $public_icon: %s (%s)\n\", \$2, \$6}{printf \"       $private_icon: %s (%s)\n%s\n\", \$3, \$4, \"$_dssh_nc\"}"
-}
+(
+  if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
+    export DEVBOX_SHELL_ENABLED=1
+    devbox -c "$ZSH_DSSH_DIR" --quiet install &> /dev/null || fatal _dssh_pfatal "failed to install devbox packages: $?"
+    local shell_env
+    shell_env="$(devbox -c "$ZSH_DSSH_DIR" --quiet shellenv | tac | sed -n '/^export /,$p' | tac | grep -v 'XPC_SERVICE_NAME')" || fatal _dssh_pfatal "failed to get devbox env: $?"
+    eval "$shell_env" || fatal _dssh_pfatal "failed to set devbox env: $?"
+  fi
 
-_dssh_prepare_dssh_locking
+  local WAS_UPDATED=false
+  local -a sort_command=("cat" "-u")
+  local format="FULL"
+  _usage() {
+    echo
+    echo "Locates servers in the inventory."
+    echo
+    echo "Usage: dwhois tags [tags ...]"
+    echo ""
+    _dssh_tag_usage
+    echo "OPTIONS:"
+    echo "    --format=[IP|INSTANCE_ID|SHORT|FULL|RAW]    format of details tp print about the servers (default: FULL)"
+    _dssh_common_usage
+  }
+  _parse_parameter() {
+    local shift_count=1
+    case "$1" in
+      -f=* | --format=*)
+        format="${1#*=}"
+        format="${format:u}"
+        case $format in
+          SHORT | INSTANCE_ID | IP | FULL | RAW)
+            ;;
+          *)
+            _dssh_perror "unsupported format [$format]"
+            _usage
+            return $_dssh_e_noargs
+            ;;
+          esac
+      ;;
+      -v | -vv | -vvv | -vvvv)
+      ;;
+      *)
+        _dssh_parse_common_parameters "$1"
+        shift_count=$?
+      ;;
+    esac
+    return $shift_count
+  }
+  function _print_hosts_full() {
+    local max_host_length="$(echo "$1" | cut -d "," -f 1 | awk '{print length}' | sort -nr | head -1)"
+    max_host_length="$((max_host_length+1))"
+    local public_icon=$'\uf0c2'
+    local private_icon=$'\uf023'
+    echo "$1" | awk -F ',' "{printf \"%s%s%s%3s: %s%-*s%s (%s)  [%s]\n\", \"$_dssh_color_prefix\", \$12, \"$_dssh_color_suffix\", NR, \"$_dssh_nc\", $max_host_length-1, \$1, \"$_dssh_gray\", \$9, \$7}{if (length(\$6) > 0) printf \"       $public_icon: %s (%s)\n\", \$2, \$6}{printf \"       $private_icon: %s (%s)\n%s\n\", \$3, \$4, \"$_dssh_nc\"}"
+  }
 
-if [[ $# -eq 0 ]]; then
-  _dssh_perror "wrong number of input parameters [$#]"
-  _usage
-  return $_dssh_e_noargs
-fi
+  _dssh_prepare_dssh_locking
 
-local python_installed=false
-local refresh_enabled=true
-local ip_mode="AUTO"
-local verbose_level=0
-local ssh_options=()
-local tags=()
-local command_string=""
-if ! _dssh_parse_parameters ".dwhoisrc" "$@"; then
-  return $_dssh_e_noerror
-fi
+  if [[ $# -eq 0 ]]; then
+    _dssh_perror "wrong number of input parameters [$#]"
+    _usage
+    return $_dssh_e_noargs
+  fi
 
-_dssh_init
+  local python_installed=false
+  local refresh_enabled=true
+  local ip_mode="AUTO"
+  local verbose_level=0
+  local ssh_options=()
+  local tags=()
+  local command_string=""
+  if ! _dssh_parse_parameters ".dwhoisrc" "$@"; then
+    return $_dssh_e_noerror
+  fi
 
-local info=""
-info="$(_dssh_resolve_target_full "${tags[@]}")"
-if [[ "$?" -eq 1 ]]; then
-  WAS_UPDATED=true
-fi
-if [ -z "$info" ]; then
-  _dssh_update_inventories
+  _dssh_init
+
+  local info=""
   info="$(_dssh_resolve_target_full "${tags[@]}")"
   if [[ "$?" -eq 1 ]]; then
     WAS_UPDATED=true
   fi
-fi
+  if [ -z "$info" ]; then
+    _dssh_update_inventories
+    info="$(_dssh_resolve_target_full "${tags[@]}")"
+    if [[ "$?" -eq 1 ]]; then
+      WAS_UPDATED=true
+    fi
+  fi
 
-if [ -z "$info" ]; then
-  _dssh_pwarn "Host '${tags[*]}' not found in inventory."
-  return $_dssh_e_noerror
-else
-  case $format in
-    IP)
-      echo "$info"  | cut -d "," -f 4
-      ;;
-    INSTANCE_ID)
-      echo "$info"  | cut -d "," -f 7
-      ;;
-    SHORT)
-      _dssh_print_menu_hosts "$(echo "$info"  | cut -d "," -f 1,4,6,9,12)"
-      ;;
-    FULL)
-      _print_hosts_full $info
-      ;;
-    RAW)
-      echo "$info"
-      ;;
-  esac
-  return $_dssh_e_noerror
-fi
+  if [ -z "$info" ]; then
+    _dssh_pwarn "Host '${tags[*]}' not found in inventory."
+    return $_dssh_e_noerror
+  else
+    case $format in
+      IP)
+        echo "$info"  | cut -d "," -f 4
+        ;;
+      INSTANCE_ID)
+        echo "$info"  | cut -d "," -f 7
+        ;;
+      SHORT)
+        _dssh_print_menu_hosts "$(echo "$info"  | cut -d "," -f 1,4,6,9,12)"
+        ;;
+      FULL)
+        _print_hosts_full $info
+        ;;
+      RAW)
+        echo "$info"
+        ;;
+    esac
+    return $_dssh_e_noerror
+  fi
+)
diff --git a/pdssh b/pdssh
--- a/pdssh
+++ b/pdssh
@@ -4,165 +4,169 @@ if [[ $0 != pdssh || -n $ZSH_SCRIPT ]]; then
     typeset ZSH_DSSH_DIR=${0:h}
 fi
 
-if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
-  devbox run -c "$ZSH_DSSH_DIR" pdssh "$@"
-  return $?
-fi
-
 set +m
 set -o pipefail
 
-local WAS_UPDATED=false
-local name_enabled=true
-local -a sort_command=()
-local list_hosts=false
-_usage() {
-  echo
-  echo "Locates and runs commands on multiple AWS servers via SSH."
-  echo
-  echo "Usage: pdssh [pdsh options] [options] tags [tags ...]"
-  echo ""
-  _dssh_tag_usage
-  echo "PDSH OPTIONS:"
-  echo "    Flags:   -b | -N | -d"
-  echo "    Options: -l | -t | -u | -f"
-  echo ""
-  echo "OPTIONS:"
-  echo "    --command=COMMAND               run the specified command and exit"
-  echo "    --list-hosts                    lists the targeted hosts and exit"
-  echo "    --sort                          sort the results by server"
-  echo "    --identity-file=FILE            file from which the identity (private key) for public key authentication is read"
-  _dssh_common_usage
-}
-_parse_parameter() {
-  local shift_count=1
-  case "$1" in
-    -N)
-      _dssh_add_ssh_option "$1"
-      name_enabled=false
-    ;;
-    -b | -d)
-      _dssh_add_ssh_option "$1"
-    ;;
-    -l | -t | -u | -f)
-      _dssh_add_ssh_option "$1 $2"
-      shift_count=2
-    ;;
-    -l\ * | -t\ * | -u\ * | -f\ *)
-      _dssh_add_ssh_option "$1"
-    ;;
-    --sort)
-      sort_command=("sort" "-s" "-t" ":")
-    ;;
-    --list-hosts)
-      list_hosts=true
-    ;;
-    --identity-file=*)
-      identity_file="${1#*=}"
-    ;;
-    -c=* | --command=*)
-      command_string="${1#*=}"
-    ;;
-    -v | -vv | -vvv | -vvvv)
-    ;;
-    *)
-      if [[ "$1" =~ ^-[bNd]+$ ]]; then
-        for char in $(echo "${1:1}" | fold -w1); do
-          _parse_parameter "-$char"
-        done
-      else
-        _dssh_parse_common_parameters "$1"
-        shift_count=$?
-      fi
-    ;;
-  esac
-  return $shift_count
-}
-_install_dependencies() {
-  if [[ "${DEVBOX_SHELL_ENABLED:-0}" == "0" ]]; then
-    which -a pdsh &>/dev/null || {
-      brew install pdsh &>/dev/null || _dssh_pfatal "failed to install pdsh: $?"
-    }
+(
+  if [[ "${DEVBOX_SHELL_ENABLED:-0}" != "1" ]] && command -v devbox &>/dev/null; then
+    export DEVBOX_SHELL_ENABLED=1
+    devbox -c "$ZSH_DSSH_DIR" --quiet install &> /dev/null || fatal _dssh_pfatal "failed to install devbox packages: $?"
+    local shell_env
+    shell_env="$(devbox -c "$ZSH_DSSH_DIR" --quiet shellenv | tac | sed -n '/^export /,$p' | tac | grep -v 'XPC_SERVICE_NAME')" || fatal _dssh_pfatal "failed to get devbox env: $?"
+    eval "$shell_env" || fatal _dssh_pfatal "failed to set devbox env: $?"
   fi
-}
 
-_dssh_prepare_dssh_locking
+  local WAS_UPDATED=false
+  local name_enabled=true
+  local -a sort_command=()
+  local list_hosts=false
+  _usage() {
+    echo
+    echo "Locates and runs commands on multiple AWS servers via SSH."
+    echo
+    echo "Usage: pdssh [pdsh options] [options] tags [tags ...]"
+    echo ""
+    _dssh_tag_usage
+    echo "PDSH OPTIONS:"
+    echo "    Flags:   -b | -N | -d"
+    echo "    Options: -l | -t | -u | -f"
+    echo ""
+    echo "OPTIONS:"
+    echo "    --command=COMMAND               run the specified command and exit"
+    echo "    --list-hosts                    lists the targeted hosts and exit"
+    echo "    --sort                          sort the results by server"
+    echo "    --identity-file=FILE            file from which the identity (private key) for public key authentication is read"
+    _dssh_common_usage
+  }
+  _parse_parameter() {
+    local shift_count=1
+    case "$1" in
+      -N)
+        _dssh_add_ssh_option "$1"
+        name_enabled=false
+      ;;
+      -b | -d)
+        _dssh_add_ssh_option "$1"
+      ;;
+      -l | -t | -u | -f)
+        _dssh_add_ssh_option "$1 $2"
+        shift_count=2
+      ;;
+      -l\ * | -t\ * | -u\ * | -f\ *)
+        _dssh_add_ssh_option "$1"
+      ;;
+      --sort)
+        sort_command=("sort" "-s" "-t" ":")
+      ;;
+      --list-hosts)
+        list_hosts=true
+      ;;
+      --identity-file=*)
+        identity_file="${1#*=}"
+      ;;
+      -c=* | --command=*)
+        command_string="${1#*=}"
+      ;;
+      -v | -vv | -vvv | -vvvv)
+      ;;
+      *)
+        if [[ "$1" =~ ^-[bNd]+$ ]]; then
+          for char in $(echo "${1:1}" | fold -w1); do
+            _parse_parameter "-$char"
+          done
+        else
+          _dssh_parse_common_parameters "$1"
+          shift_count=$?
+        fi
+      ;;
+    esac
+    return $shift_count
+  }
+  _install_dependencies() {
+    if [[ "${DEVBOX_SHELL_ENABLED:-0}" == "0" ]]; then
+      which -a pdsh &>/dev/null || {
+        brew install pdsh &>/dev/null || _dssh_pfatal "failed to install pdsh: $?"
+      }
+    fi
+  }
 
-if [[ $# -eq 0 ]]; then
-  _dssh_perror "wrong number of input parameters [$#]"
-  _usage
-  return $_dssh_e_noargs
-fi
+  _dssh_prepare_dssh_locking
 
-local python_installed=false
-local refresh_enabled=true
-local verbose_level=0
-local ssh_options=()
-local tags=()
-local command_string=""
-local identity_file=""
-if ! _dssh_parse_parameters ".pdsshrc" "$@"; then
-  return $_dssh_e_noerror
-fi
-if [[ "${#sort_command}" -gt 0 && "$name_enabled" == "true" ]]; then
-  sort_command+=("-k" "1,1")
-fi
-
-_dssh_init
-
-local addr=""
-local desc=""
-if [[ ${#tags[@]} -eq 1 && "${tags[1]}" =~ $_dssh_public_fqdn_target ]]; then
-  addr="${tags[1]}"
-else
-  local info=""
-  info="$(_dssh_resolve_target "${tags[@]}")"
-  if [[ "$?" -eq 1 ]]; then
-    WAS_UPDATED=true
+  if [[ $# -eq 0 ]]; then
+    _dssh_perror "wrong number of input parameters [$#]"
+    _usage
+    return $_dssh_e_noargs
   fi
-  if [ -z "$info" ]; then
-    _dssh_update_inventories
+
+  local python_installed=false
+  local refresh_enabled=true
+  local verbose_level=0
+  local ssh_options=()
+  local tags=()
+  local command_string=""
+  local identity_file=""
+  if ! _dssh_parse_parameters ".pdsshrc" "$@"; then
+    return $_dssh_e_noerror
+  fi
+  if [[ "${#sort_command}" -gt 0 && "$name_enabled" == "true" ]]; then
+    sort_command+=("-k" "1,1")
+  fi
+
+  _dssh_init
+
+  local addr=""
+  local desc=""
+  if [[ ${#tags[@]} -eq 1 && "${tags[1]}" =~ $_dssh_public_fqdn_target ]]; then
+    addr="${tags[1]}"
+  else
+    local info=""
     info="$(_dssh_resolve_target "${tags[@]}")"
     if [[ "$?" -eq 1 ]]; then
       WAS_UPDATED=true
     fi
     if [ -z "$info" ]; then
-      _dssh_pwarn "Host '${tags[*]}' not found in inventory.  Attempting to connect anyway..."
-      addr="${tags[*]}"
+      _dssh_update_inventories
+      info="$(_dssh_resolve_target "${tags[@]}")"
+      if [[ "$?" -eq 1 ]]; then
+        WAS_UPDATED=true
+      fi
+      if [ -z "$info" ]; then
+        _dssh_pwarn "Host '${tags[*]}' not found in inventory.  Attempting to connect anyway..."
+        addr="${tags[*]}"
+      fi
+    fi
+    if [[ "$addr" == "" ]]; then
+      addr=$(echo "$info" | awk -F, '{printf("%s,",$2)}' | sed 's/,\s*$//')
     fi
   fi
-  if [[ "$addr" == "" ]]; then
-    addr=$(echo "$info" | awk -F, '{printf("%s,",$2)}' | sed 's/,\s*$//')
+
+  if [[ "$list_hosts" == "true" ]]; then
+    _dssh_print_menu_hosts $info
+    return $_dssh_e_noerror
   fi
-fi
 
-if [[ "$list_hosts" == "true" ]]; then
-  _dssh_print_menu_hosts $info
-  return $_dssh_e_noerror
-fi
-
-echo "" 1>&2
-local server_count="$(echo "$addr" | awk -F, '{ print NF; exit }')"
-local server_message="$server_count server"
-if [[ "$server_count" -ne 1 ]]; then
-  server_message="${server_message}s"
-fi
-local connection_message="Running command against $server_message..."
-local -a ssh_command=( "pdsh" "-S" "-R" "ssh")
-if [[ "${#ssh_options[@]}" -gt 0 ]]; then
-  read -rA opts <<<"${ssh_options[@]}"
-  for opt in "${opts[@]}"; do
-    ssh_command+=( "$opt" )
-  done
-fi
-ssh_command+=( "-w" "$addr" )
-if [[ "$command_string" != "" ]]; then
-  ssh_command+=( "${command_string}" )
-fi
-_install_dependencies
-_dssh_pverbose "$connection_message"
-local awk_map="my \$hosts_file;"
-for f in $HOME/.aws-hosts.*; do
+  echo "" 1>&2
+  local server_count="$(echo "$addr" | awk -F, '{ print NF; exit }')"
+  local server_message="$server_count server"
+  if [[ "$server_count" -ne 1 ]]; then
+    server_message="${server_message}s"
+  fi
+  local connection_message="Running command against $server_message..."
+  local -a ssh_command=( "pdsh" "-S" "-R" "ssh")
+  if [[ "${#ssh_options[@]}" -gt 0 ]]; then
+    read -rA opts <<<"${ssh_options[@]}"
+    for opt in "${opts[@]}"; do
+      ssh_command+=( "$opt" )
+    done
+  fi
+  ssh_command+=( "-w" "$addr" )
+  if [[ "$command_string" != "" ]]; then
+    ssh_command+=( "${command_string}" )
+  fi
+  _install_dependencies
+  _dssh_pverbose "$connection_message"
+  local awk_map="my \$hosts_file;"
+  for f in $HOME/.aws-hosts.*; do
 awk_map=$(\cat <<EOF
 $awk_map
 open(\$hosts_file, '$f') || die 'Cannot open file "$f".';
@@ -186,8 +190,8 @@ while (<\$hosts_file>) {
 }
 EOF
 )
-done
-local enrich_script=$(\cat <<EOF
+  done
+  local enrich_script=$(\cat <<EOF
 #!/usr/bin/perl
 use strict;
 use warnings;
@@ -221,13 +225,14 @@ while (<>) {
 }
 EOF
 )
-local additional_ssh_args=""
-if [[ "${#identity_file}" -gt 0 ]]; then
-  additional_ssh_args=" -o IdentitiesOnly=yes -i $identity_file"
-fi
-if [[ "${#sort_command}" -gt 0 ]]; then
-  env PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR$additional_ssh_args" ${ssh_command[@]} 2>&1 | perl -e "$enrich_script" | ${sort_command[@]}
-else
-  env PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR$additional_ssh_args" ${ssh_command[@]} 2>&1 | perl -e "$enrich_script"
-fi
-return $?
+  local additional_ssh_args=""
+  if [[ "${#identity_file}" -gt 0 ]]; then
+    additional_ssh_args=" -o IdentitiesOnly=yes -i $identity_file"
+  fi
+  if [[ "${#sort_command}" -gt 0 ]]; then
+    env PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR$additional_ssh_args" ${ssh_command[@]} 2>&1 | perl -e "$enrich_script" | ${sort_command[@]}
+  else
+    env PDSH_SSH_ARGS_APPEND="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR$additional_ssh_args" ${ssh_command[@]} 2>&1 | perl -e "$enrich_script"
+  fi
+  return $?
+)
